general.import = ["~/.config/alacritty/themes/themes/rose-pine.toml"]

[env]
# to be compatible with legacy machines
TERM = "xterm-256color"
# TERM = "alacritty"

[window]
opacity = 1

[font]
size = 14.0
offset.x = 0
offset.y = 5

[font.normal]
family = "AnonymicePro Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[terminal.shell]
program = "zellij"
args = ["-l", "welcome"]
