[general]
import = ["~/.config/alacritty/themes/themes/rose_pine.toml"]

[env]
# to be compatible with legacy machines
TERM = "xterm-256color"
# TERM = "alacritty"

[window]
opacity = 1

[font]
size = 15
offset.x = 0
offset.y = 3
normal = { family = "AnonymicePro Nerd Font Mono", style = "Regular" }
bold = { family = "AnonymicePro Nerd Font Mono", style = "Bold" }
italic = { family = "AnonymicePro Nerd Font Mono", style = "Italic" }

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[terminal.shell]
program = "zellij"
args = ["-l", "welcome"]
