import = ["~/.config/alacritty/themes/themes/blood_moon.toml"]

[env]
# to be compatible with legacy machines
TERM = "xterm-256color"
# TERM = "alacritty"

[window]
opacity = 0.8

[font]
size = 15.0
offset.x = 0
offset.y = 5

[font.normal]
family = "AnonymicePro Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
