theme = "rose_pine_moon"

[editor]
line-number = "relative"
rulers = [80, 120]
mouse = true
auto-save = true
# Show currently open buffers, only when more than one exists.
bufferline = "multiple"
# Highlight all lines with a cursor
cursorline = true
# Force the theme to show colors
true-color = true
color-modes = true
insert-final-newline = false
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
# Minimum severity to show a diagnostic on other lines:
# other-lines = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.statusline]
left = ["mode", "diagnostics", "spinner", "version-control"]
center = ["file-base-name", "file-modification-indicator"]
right = [
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true
# Show LSP messages below statusline
display-messages = true

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
# Yank diagnostic(s) under primary cursor to register, or clipboard by default
z = ":yank-diagnostic"
# Toggle inline diagnostics for the cursor line
l = ":toggle inline-diagnostics.cursor-line disable error"
# Toggle end-of-line diagnostics
e = ":toggle end-of-line-diagnostics disable hint"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"
[editor.whitespace.characters]
tabpad = "·"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "╎" "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.soft-wrap]
enable = true

# Saves on Esc key
[keys.normal]
"esc" = ["collapse_selection", ":w"]
[keys.select]
"esc" = ["collapse_selection", "normal_mode", ":w"]
[keys.insert]
"esc" = ["normal_mode", ":w"]
