inherits = "boo_berry"

# "ui.background" = { bg = "berry_saturated" }
# Override the theming for "keyword"s:
"ui.virtual.inlay-hint" = { fg = "peony", bg = "peony_10" }
# "ui.cursorline.primary" = { bg = "rain_10" }
# "ui.selection.primary" = { bg = "rain" }

# Override colors in the palette:
[palette]
berry = "#0c000d"
# berry_dim = "#3A2A4D"
# berry_saturated = "#0c000d"
peony = "#8C1396"
peony_10 = "#19001B"
