inherits = "rose_pine"

# Override the theming for "keyword"s:
"ui.virtual.inlay-hint" = { fg = "hint_fg", bg = "hint_bg" }
# "ui.cursorline.primary" = { bg = "rain_10" }
# "ui.selection.primary" = { bg = "rain" }

# Override colors in the palette:
[palette]
base = "#0d0c12"
text = "#D4CFFF"
iris = "#ba82ff"
hint_fg = "#908caa"
hint_bg = "#1f1d2e"
